=== muhliz25/cs-codebook/07 XML/138 XML-Dateien über ein DataSet lesen/bin/Debug/Persons.xsd
<?xml version="1.0" standalone="yes"?>
<xs:schema 
  xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" 
  xmlns:xs="http://www.w3.org/2001/XMLSchema" id="persons">
  <xs:element name="persons">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded">
        <xs:element name="person">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="firstname" type="xs:string"/>
              <xs:element name="lastname" type="xs:string"/>
              <xs:element name="vehicleId" type="xs:int"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:int" use="required"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="vehicle">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="type" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:int" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== muhliz25/cs-codebook/07 XML/138 XML-Dateien über ein DataSet lesen/bin/Debug/Persons.xml
<?xml version="1.0" encoding="utf-8"?>
<persons 
  xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
   xsi:noNamespaceSchemaLocation="Persons.xsd">

  <person id="1000">
    <firstname>Zaphod</firstname>
    <lastname>Beeblebrox</lastname>
    <vehicleId>1</vehicleId>
  </person>

  <person id="1001">
    <firstname>Tricia</firstname>
    <lastname>McMillan</lastname>
    <vehicleId>2</vehicleId>
  </person>

  <vehicle id="1">
    <type>Spaceship</type>
  </vehicle>

  <vehicle id="2">
    <type>Car</type>
  </vehicle>
</persons>
