<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE persons [
<!ELEMENT persons (person)+>
<!ELEMENT person (firstname, lastname, type)>
<!ATTLIST person id CDATA #REQUIRED>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT type (#PCDATA)>
]>

<persons>
   <person id="1000">
      <firstname>Zaphod</firstname>
      <lastname>Beeblebrox</lastname>
      <type>Alien</type>
   </person>
   <person id="1001">
      <firstname>Ford</firstname>
      <lastname>Prefect</lastname>
      <type>Alien</type>
   </person>
   <person id="1002">
      <firstname>Tricia</firstname>
      <lastname>McMillan</lastname>
      <type>Earthling</type>
   </person>
   <person id="1003">
      <firstname>Arthur</firstname>
      <lastname>Dent</lastname>
      <type>Earthling</type>
   </person>
</persons>
